-- CLEAN SLATE: Reset public schema before seeding
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;

--
-- PostgreSQL database dump
--

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: absence_reasons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.absence_reasons (
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    reason text,
    source character varying(255) NOT NULL,
    student_name character varying(255) NOT NULL,
    subject_name character varying(255) NOT NULL
);


--
-- Name: absence_reasons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.absence_reasons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.absence_reasons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admission_weights; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.admission_weights (
    consistency_weight double precision NOT NULL,
    entrance_weight double precision NOT NULL,
    marks_weight double precision NOT NULL,
    variance_penalty double precision NOT NULL,
    batch_id bigint NOT NULL,
    id bigint NOT NULL,
    insights text,
    weight_changes text
);


--
-- Name: admission_weights_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admission_weights ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admission_weights_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agent_action_outcomes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.agent_action_outcomes (
    effectiveness_score double precision NOT NULL,
    id bigint NOT NULL,
    "timestamp" timestamp(6) without time zone,
    reasoning character varying(2000),
    agent_name character varying(255),
    context_health character varying(255),
    status character varying(255),
    task_id character varying(255),
    tool_name character varying(255)
);


--
-- Name: agent_action_outcomes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agent_action_outcomes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agent_action_outcomes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agent_audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.agent_audit_logs (
    confidence double precision NOT NULL,
    entity_id bigint,
    execution_time_ms bigint NOT NULL,
    id bigint NOT NULL,
    "timestamp" timestamp(6) without time zone,
    goal character varying(2048),
    reasoning character varying(5000),
    tool_input character varying(5000),
    tool_output character varying(5000),
    action character varying(255),
    agent_name character varying(255),
    entity_type character varying(255),
    full_prompt text,
    full_response text,
    task_id character varying(255)
);


--
-- Name: agent_audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agent_audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agent_audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agent_decision_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.agent_decision_logs (
    entity_id bigint,
    id bigint NOT NULL,
    "timestamp" timestamp(6) without time zone,
    decision character varying(5000),
    reasoning character varying(5000),
    agent_name character varying(255),
    entity_type character varying(255)
);


--
-- Name: agent_decision_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agent_decision_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agent_decision_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agent_experiences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.agent_experiences (
    score double precision NOT NULL,
    id bigint NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    action character varying(100) NOT NULL,
    goal_id character varying(255) NOT NULL,
    outcome text NOT NULL,
    result text NOT NULL
);


--
-- Name: agent_experiences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agent_experiences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agent_experiences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agent_strategies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.agent_strategies (
    confidence_score double precision NOT NULL,
    usage_count integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    goal_context character varying(100) NOT NULL,
    strategy text NOT NULL
);


--
-- Name: agent_strategies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.agent_strategies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agent_strategies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agent_task_context; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.agent_task_context (
    context_value character varying(2048),
    context_key character varying(255) NOT NULL,
    task_id character varying(255) NOT NULL
);


--
-- Name: agent_tasks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.agent_tasks (
    requires_manual_approval boolean,
    retry_count integer,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    entity_id bigint,
    updated_at timestamp(6) without time zone,
    goal character varying(2048),
    agent_name character varying(255),
    entity_type character varying(255),
    error_message character varying(255),
    override_action character varying(255),
    override_parameters_json text,
    override_reasoning character varying(255),
    status character varying(255),
    task_id character varying(255) NOT NULL
);


--
-- Name: app_workflow_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.app_workflow_state (
    application_id bigint NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    current_stage character varying(255) NOT NULL
);


--
-- Name: app_workflow_state_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.app_workflow_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_workflow_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: applications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.applications (
    academic_score double precision NOT NULL,
    confidence_score double precision,
    consistency double precision,
    documents_verified boolean NOT NULL,
    entrance_score double precision,
    exam_time_slot time(6) without time zone,
    final_score double precision,
    marks double precision,
    neet_score double precision,
    ocr_academic_score double precision,
    ocr_verified boolean,
    school_marks double precision,
    variance double precision,
    batch_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    exam_hall_id bigint,
    id bigint NOT NULL,
    university_id bigint,
    updated_at timestamp(6) without time zone,
    application_data text,
    decision_reason text,
    email character varying(255) NOT NULL,
    exam_password character varying(255),
    extracted_marks text,
    file_path character varying(255),
    full_name character varying(255) NOT NULL,
    ocr_audit_log text,
    ocr_transcript text,
    parent_email character varying(255),
    profile_photo text,
    status character varying(255) NOT NULL,
    applicant_user_id bigint
);


--
-- Name: applications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.applications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.assessments (
    marks double precision NOT NULL,
    id bigint NOT NULL,
    slot_enrollment_id bigint NOT NULL
);


--
-- Name: assessments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assessments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.attendance (
    date date NOT NULL,
    present boolean NOT NULL,
    id bigint NOT NULL,
    slot_enrollment_id bigint NOT NULL
);


--
-- Name: attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_interventions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.attendance_interventions (
    baseline_attendance double precision,
    improvement_score double precision,
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    last_action_date timestamp(6) without time zone NOT NULL,
    student_id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    current_level character varying(255) NOT NULL,
    student_feedback text,
    CONSTRAINT attendance_interventions_current_level_check CHECK (((current_level)::text = ANY ((ARRAY['NONE'::character varying, 'EMAIL_STUDENT'::character varying, 'SMS_STUDENT'::character varying, 'EMAIL_PARENT'::character varying, 'DIRECT_CALL'::character varying, 'ACADEMIC_PROBATION'::character varying])::text[])))
);


--
-- Name: attendance_interventions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendance_interventions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_interventions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: batch_programs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.batch_programs (
    total_credits_required integer,
    batch_id bigint NOT NULL,
    id bigint NOT NULL,
    program_id bigint NOT NULL,
    subjects text
);


--
-- Name: batch_programs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.batch_programs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.batch_programs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: batch_workflow_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.batch_workflow_state (
    batch_id bigint NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    last_event character varying(255) NOT NULL,
    phase character varying(255) NOT NULL
);


--
-- Name: batch_workflow_state_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.batch_workflow_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.batch_workflow_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.batches (
    attendance_shortage double precision,
    duration integer,
    end_year integer NOT NULL,
    exam_weightage integer,
    intake_capacity integer,
    late_fee double precision,
    library_dues double precision,
    min_academic_cutoff double precision,
    registration_fee double precision,
    seat_capacity integer,
    semester_fee double precision,
    start_year integer NOT NULL,
    tuition_fee double precision,
    waitlist_capacity integer,
    id bigint NOT NULL,
    university_id bigint,
    application_deadline character varying(255),
    batch_code character varying(255),
    departments text,
    description text,
    document_requirements text,
    entrance_exam character varying(255),
    name character varying(255) NOT NULL,
    scholarships text,
    status character varying(255) NOT NULL
);


--
-- Name: batches_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: candidates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.candidates (
    id bigint NOT NULL,
    university_id bigint,
    department character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    extracted_text text,
    full_name character varying(255) NOT NULL,
    reasoning text,
    resume_url character varying(255),
    status character varying(255) NOT NULL
);


--
-- Name: candidates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.candidates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.candidates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: career_outcomes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.career_outcomes (
    id bigint NOT NULL,
    student_id bigint NOT NULL,
    description character varying(255),
    outcome_type character varying(255) NOT NULL
);


--
-- Name: career_outcomes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.career_outcomes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.career_outcomes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: certificates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.certificates (
    id bigint NOT NULL,
    issued_at timestamp(6) without time zone NOT NULL,
    student_id bigint NOT NULL,
    certificate_code character varying(255) NOT NULL,
    degree_name character varying(255) NOT NULL
);


--
-- Name: certificates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.certificates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.certificates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: counseling_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.counseling_sessions (
    session_date date,
    application_id bigint NOT NULL,
    batch_id bigint NOT NULL,
    id bigint NOT NULL,
    status character varying(255),
    time_slot character varying(255)
);


--
-- Name: counseling_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.counseling_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.counseling_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_exams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.course_exams (
    duration_minutes integer NOT NULL,
    exam_hall_id bigint NOT NULL,
    id bigint NOT NULL,
    start_time timestamp(6) without time zone NOT NULL,
    subject_offering_id bigint NOT NULL,
    questions_json text,
    status character varying(255) NOT NULL
);


--
-- Name: course_exams_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_exams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_exams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.email_log (
    retry_count integer NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    sent_at timestamp(6) without time zone,
    body text,
    error_message character varying(255),
    recipient character varying(255),
    status character varying(255),
    subject character varying(255)
);


--
-- Name: email_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.email_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: enrollments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.enrollments (
    batch_id bigint NOT NULL,
    enrolled_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    student_id bigint NOT NULL
);


--
-- Name: enrollments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.enrollments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enrollments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: entrance_exam_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.entrance_exam_sessions (
    exam_date date NOT NULL,
    exam_score integer,
    exam_time time(6) without time zone NOT NULL,
    score double precision,
    seat_number integer NOT NULL,
    application_id bigint NOT NULL,
    batch_id bigint,
    id bigint NOT NULL,
    room character varying(255) NOT NULL
);


--
-- Name: entrance_exam_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.entrance_exam_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entrance_exam_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exam_halls; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.exam_halls (
    capacity integer NOT NULL,
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: exam_halls_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exam_halls ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_halls_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exam_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.exam_questions (
    id bigint NOT NULL,
    subject_offering_id bigint NOT NULL,
    optiona character varying(300) NOT NULL,
    optionb character varying(300) NOT NULL,
    optionc character varying(300) NOT NULL,
    optiond character varying(300) NOT NULL,
    question_text character varying(500) NOT NULL,
    correct_option character varying(255) NOT NULL
);


--
-- Name: exam_questions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exam_questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exam_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.exam_results (
    rank integer,
    score double precision NOT NULL,
    application_id bigint NOT NULL,
    id bigint NOT NULL
);


--
-- Name: exam_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exam_results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exam_schedules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.exam_schedules (
    total_capacity integer,
    batch_id bigint NOT NULL,
    exam_date timestamp(6) without time zone,
    id bigint NOT NULL,
    hall_allocations text,
    status character varying(255)
);


--
-- Name: exam_schedules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exam_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exam_submissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.exam_submissions (
    score integer NOT NULL,
    id bigint NOT NULL,
    slot_enrollment_id bigint NOT NULL,
    submitted_at timestamp(6) without time zone NOT NULL,
    answers character varying(5000) NOT NULL
);


--
-- Name: exam_submissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exam_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: faculty; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.faculty (
    id bigint NOT NULL,
    university_id bigint,
    user_id bigint NOT NULL,
    department character varying(255),
    full_name character varying(255)
);


--
-- Name: faculty_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.faculty ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faculty_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: failed_task; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.failed_task (
    entity_id bigint,
    failed_at timestamp(6) without time zone,
    id bigint NOT NULL,
    error_message character varying(4096),
    agent_name character varying(255),
    entity_type character varying(255),
    task_id character varying(255),
    stack_trace text
);


--
-- Name: failed_task_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.failed_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.failed_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feature_performance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.feature_performance (
    avg_outcome_score double precision NOT NULL,
    batch_id bigint NOT NULL,
    id bigint NOT NULL,
    feature_name character varying(255) NOT NULL
);


--
-- Name: feature_performance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feature_performance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feature_performance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: goals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.goals (
    priority integer NOT NULL,
    urgency_score double precision NOT NULL,
    created_at timestamp(6) with time zone,
    deadline timestamp(6) with time zone,
    id bigint NOT NULL,
    last_pursued_at timestamp(6) without time zone,
    updated_at timestamp(6) with time zone,
    status character varying(20) NOT NULL,
    type character varying(50) NOT NULL,
    depends_on_goal_ids character varying(512),
    abandon_reason character varying(1024),
    description text,
    goal_statement character varying(2048),
    agent_name character varying(255),
    category character varying(255),
    name character varying(255) NOT NULL,
    constraints jsonb,
    progress_metrics jsonb,
    success_criteria jsonb,
    CONSTRAINT goals_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PAUSED'::character varying, 'ABANDONED'::character varying, 'COMPLETED'::character varying, 'PARTIALLY_COMPLETED'::character varying, 'FAILED'::character varying, 'TIMEOUT'::character varying])::text[]))),
    CONSTRAINT goals_type_check CHECK (((type)::text = ANY ((ARRAY['ADMISSIONS'::character varying, 'ATTENDANCE'::character varying, 'FINANCE'::character varying, 'ACADEMICS'::character varying, 'HR'::character varying])::text[])))
);


--
-- Name: goals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.goals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: graduation_candidates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.graduation_candidates (
    credits_achieved integer NOT NULL,
    id bigint NOT NULL,
    identified_at timestamp(6) without time zone NOT NULL,
    processed_at timestamp(6) without time zone,
    student_id bigint NOT NULL,
    status character varying(255) NOT NULL
);


--
-- Name: graduation_candidates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.graduation_candidates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.graduation_candidates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interview_schedules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.interview_schedules (
    candidate_id bigint NOT NULL,
    id bigint NOT NULL,
    interviewer_id bigint NOT NULL,
    scheduled_at timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL
);


--
-- Name: interview_schedules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interview_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interview_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: join_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.join_requests (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    university_id bigint NOT NULL,
    user_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT join_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: join_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.join_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.join_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parent_notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.parent_notifications (
    sentiment_score double precision,
    id bigint NOT NULL,
    sent_at timestamp(6) without time zone NOT NULL,
    student_id bigint NOT NULL,
    ai_message text NOT NULL,
    parent_email character varying(255) NOT NULL,
    parent_reply text,
    root_cause character varying(255),
    type character varying(255) NOT NULL
);


--
-- Name: parent_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.parent_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parent_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: programs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.programs (
    id bigint NOT NULL,
    code character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: programs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.programs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.programs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: question_bank; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.question_bank (
    id bigint NOT NULL,
    question_text character varying(1000) NOT NULL,
    correct_option character varying(255) NOT NULL,
    optiona character varying(255) NOT NULL,
    optionb character varying(255) NOT NULL,
    optionc character varying(255) NOT NULL,
    optiond character varying(255) NOT NULL,
    subject_name character varying(255) NOT NULL
);


--
-- Name: question_bank_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.question_bank ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_bank_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.rooms (
    capacity integer NOT NULL,
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: semester_exam_schedules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.semester_exam_schedules (
    exam_date date,
    admin_approved_at timestamp(6) without time zone,
    id bigint NOT NULL,
    subject_offering_id bigint NOT NULL,
    hall_allocations character varying(5000),
    room character varying(255),
    status character varying(255)
);


--
-- Name: semester_exam_schedules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.semester_exam_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.semester_exam_schedules_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: slot_enrollments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.slot_enrollments (
    credits_earned integer,
    exam_eligible boolean,
    exam_marks double precision,
    id bigint NOT NULL,
    student_id bigint,
    subject_offering_id bigint,
    enrollment_date character varying(255),
    status character varying(255)
);


--
-- Name: slot_enrollments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.slot_enrollments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.slot_enrollments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: staff; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.staff (
    active boolean NOT NULL,
    salary double precision,
    id bigint NOT NULL,
    department character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    role character varying(255) NOT NULL
);


--
-- Name: staff_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.staff ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.staff_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: strategic_lessons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.strategic_lessons (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    source_batch_id bigint,
    lesson text
);


--
-- Name: strategic_lessons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.strategic_lessons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.strategic_lessons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_credits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.student_credits (
    earned_credits integer NOT NULL,
    pending_credits integer NOT NULL,
    id bigint NOT NULL,
    student_id bigint NOT NULL
);


--
-- Name: student_credits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_credits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_credits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_outcomes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.student_outcomes (
    attendance_pct double precision,
    first_exam_score double precision,
    id bigint NOT NULL,
    student_id bigint NOT NULL
);


--
-- Name: student_outcomes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_outcomes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_outcomes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.students (
    credits_earned integer,
    application_id bigint,
    batch_id bigint,
    batch_program_id bigint,
    id bigint NOT NULL,
    program_id bigint,
    university_id bigint,
    user_id bigint NOT NULL,
    department character varying(255),
    full_name character varying(255),
    notes text,
    parent_email character varying(255),
    parent_name character varying(255),
    parent_phone character varying(255),
    profile_photo text,
    risk_level character varying(255),
    roll_number character varying(255)
);


--
-- Name: students_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subject_offerings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.subject_offerings (
    active boolean NOT NULL,
    capacity integer NOT NULL,
    credits integer NOT NULL,
    locked_for_exam boolean DEFAULT false NOT NULL,
    batch_id bigint NOT NULL,
    faculty_id bigint NOT NULL,
    id bigint NOT NULL,
    prerequisite character varying(255),
    room character varying(255),
    slot character varying(255) NOT NULL,
    status character varying(255) DEFAULT 'APPROVED'::character varying NOT NULL,
    subject_name character varying(255) NOT NULL
);


--
-- Name: subject_offerings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subject_offerings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subject_offerings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: system_policies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.system_policies (
    policy_value double precision NOT NULL,
    last_updated timestamp(6) without time zone,
    description character varying(1000),
    policy_key character varying(255) NOT NULL
);


--
-- Name: universities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.universities (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    description character varying(1000),
    admin_email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    subdomain character varying(255),
    logo_url character varying(1000)
);


--
-- Name: universities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.universities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.universities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: university_goals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.university_goals (
    id bigint NOT NULL,
    abandon_reason character varying(1024),
    agent_name character varying(255) NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    depends_on_goal_ids character varying(512),
    goal_statement character varying(2048) NOT NULL,
    last_pursued_at timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    priority integer NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    urgency_score double precision NOT NULL
);


--
-- Name: university_goals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.university_goals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.university_goals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.users (
    id bigint NOT NULL,
    university_id bigint,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workflow_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.workflow_state (
    id bigint NOT NULL,
    application_id bigint NOT NULL,
    current_stage character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    batch_id bigint NOT NULL,
    last_event character varying(255) NOT NULL,
    phase character varying(255) NOT NULL
);


--
-- Name: workflow_state_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.workflow_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: absence_reasons; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: admission_weights; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.admission_weights (consistency_weight, entrance_weight, marks_weight, variance_penalty, batch_id, id, insights, weight_changes) VALUES (0.2, 0.3, 0.4, 0.1, 1, 1, NULL, NULL);


--
-- Data for Name: agent_action_outcomes; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: agent_audit_logs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: agent_decision_logs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: agent_experiences; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: agent_strategies; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: agent_task_context; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: agent_tasks; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: app_workflow_state; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: applications; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: assessments; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: attendance; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: attendance_interventions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: batch_programs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: batch_workflow_state; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: batches; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.batches (attendance_shortage, duration, end_year, exam_weightage, intake_capacity, late_fee, library_dues, min_academic_cutoff, registration_fee, seat_capacity, semester_fee, start_year, tuition_fee, waitlist_capacity, id, university_id, application_deadline, batch_code, departments, description, document_requirements, entrance_exam, name, scholarships, status) VALUES (50, 4, 2030, 60, 5, 10, 2, NULL, NULL, 5, NULL, 2026, NULL, 3, 1, 1, '2026-04-06', 'testing-batch', NULL, '', '["12th Board Exam Result"]', 'SAT Advanced', 'testing batch', '[]', 'ADMISSIONS_OPEN');


--
-- Data for Name: candidates; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: career_outcomes; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: certificates; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: counseling_sessions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: course_exams; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: email_log; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: enrollments; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: entrance_exam_sessions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: exam_halls; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: exam_questions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: exam_results; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: exam_schedules; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: exam_submissions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: faculty; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: failed_task; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: feature_performance; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: goals; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: graduation_candidates; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: interview_schedules; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: join_requests; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: parent_notifications; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: programs; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: question_bank; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: rooms; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: semester_exam_schedules; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: slot_enrollments; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: staff; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: strategic_lessons; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: student_credits; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: student_outcomes; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: students; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: subject_offerings; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: system_policies; Type: TABLE DATA; Schema: public; Owner: -
--

-- No system policies to seed


--
-- Data for Name: universities; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.universities (created_at, id, description, admin_email, name, subdomain, logo_url) VALUES ('2026-04-06 09:04:40.155529', 1, '', 'universityos888@gmail.com', 'SAVEETHA SCHOOL OF ENGINEERING', 'simats', 'https://drive.google.com/file/d/1i5IV2-vG7jtKjBVH493I-bJsnkixsips/view?usp=sharing');


--
-- Data for Name: university_goals; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.users (id, university_id, email, password, role) VALUES 
(8, 1, 'sriharir1120.sse@saveetha.com', '$2a$10$bAiPfaWUPDLltYoEbgv64eOKzldgubVy5r17OEd18Ll4bwsIfDK96', 'APPLICANT'),
(3, 1, 'sriharir1711@gmail.com', '$2a$10$ZjNIxFIHRx/49uMeYdj6Su0hxBcjgHqL3x0Fg.p01B9/M.r8PkO9K', 'APPLICANT'),
(4, 1, 'srihari02045@gmail.com', '$2a$10$0O/xweZF9mhthhjIROtsweinIP4odDjWuhEnwvvZ9IfUEbzJPRMWC', 'APPLICANT'),
(1, NULL, 'superadmin@unios.com', '$2a$10$aYxrieIT68odkgxSr5ZBkuGHPEBpbzZtKR0P61nTm21G97jXqPMXS', 'ADMIN'),
(2, 1, 'universityos888@gmail.com', '$2a$10$Vxem..h1Qin6ZbV03zcEb.sLBQJsVS.H5gNPxOt6BvNz7n07g6j2S', 'ADMIN'),
(5, 1, 'imvengeance1711@gmail.com', '$2a$10$VXXHWWjtP0vt2GkCwIbM/urj82PojauAO3uac2cc3YaITFzLp6bwW', 'APPLICANT'),
(6, 1, 'ramanjeeva678@gmail.com', '$2a$10$ONz/9V1u6hWt4TNCFMI85OvoHybou1A2sirSiDWCLQjgJoh0L8B3y', 'APPLICANT'),
(7, 1, 'steercom.in@gmail.com', '$2a$10$iQod4ceey0jFRfFELOY6Een/Pg9ILEz5f6Vv/WUvHjq3VuyTg2m.2', 'APPLICANT');


--
-- Data for Name: workflow_state; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Name: absence_reasons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.absence_reasons_id_seq', 1, false);


--
-- Name: admission_weights_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.admission_weights_id_seq', 1, true);


--
-- Name: agent_action_outcomes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.agent_action_outcomes_id_seq', 1, false);


--
-- Name: agent_audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.agent_audit_logs_id_seq', 1, false);


--
-- Name: agent_decision_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.agent_decision_logs_id_seq', 1, false);


--
-- Name: agent_experiences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.agent_experiences_id_seq', 1, false);


--
-- Name: agent_strategies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.agent_strategies_id_seq', 1, false);


--
-- Name: app_workflow_state_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.app_workflow_state_id_seq', 1, false);


--
-- Name: applications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.applications_id_seq', 150, true);


--
-- Name: assessments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.assessments_id_seq', 1, false);


--
-- Name: attendance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.attendance_id_seq', 1, false);


--
-- Name: attendance_interventions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.attendance_interventions_id_seq', 1, false);


--
-- Name: batch_programs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.batch_programs_id_seq', 4, true);


--
-- Name: batch_workflow_state_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.batch_workflow_state_id_seq', 1, false);


--
-- Name: batches_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.batches_id_seq', 1, true);


--
-- Name: candidates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.candidates_id_seq', 1, false);


--
-- Name: career_outcomes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.career_outcomes_id_seq', 1, false);


--
-- Name: certificates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.certificates_id_seq', 1, false);


--
-- Name: counseling_sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.counseling_sessions_id_seq', 1, false);


--
-- Name: course_exams_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.course_exams_id_seq', 1, false);


--
-- Name: email_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.email_log_id_seq', 53, true);


--
-- Name: enrollments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.enrollments_id_seq', 1, false);


--
-- Name: entrance_exam_sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.entrance_exam_sessions_id_seq', 1, false);


--
-- Name: exam_halls_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exam_halls_id_seq', 100, true);


--
-- Name: exam_questions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exam_questions_id_seq', 1, false);


--
-- Name: exam_results_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exam_results_id_seq', 1, false);


--
-- Name: exam_schedules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exam_schedules_id_seq', 1, false);


--
-- Name: exam_submissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.exam_submissions_id_seq', 1, false);


--
-- Name: faculty_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.faculty_id_seq', 1, false);


--
-- Name: failed_task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.failed_task_id_seq', 1, false);


--
-- Name: feature_performance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.feature_performance_id_seq', 1, false);


--
-- Name: goals_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.goals_id_seq', 164, true);


--
-- Name: graduation_candidates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.graduation_candidates_id_seq', 1, false);


--
-- Name: interview_schedules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.interview_schedules_id_seq', 1, false);


--
-- Name: join_requests_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.join_requests_id_seq', 1, false);


--
-- Name: parent_notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.parent_notifications_id_seq', 1, false);


--
-- Name: programs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.programs_id_seq', 4, true);


--
-- Name: question_bank_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.question_bank_id_seq', 1, false);


--
-- Name: rooms_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.rooms_id_seq', 10, true);


--
-- Name: semester_exam_schedules_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.semester_exam_schedules_id_seq', 1, false);


--
-- Name: slot_enrollments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.slot_enrollments_id_seq', 1, false);


--
-- Name: staff_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.staff_id_seq', 1, false);


--
-- Name: strategic_lessons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.strategic_lessons_id_seq', 1, false);


--
-- Name: student_credits_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.student_credits_id_seq', 1, false);


--
-- Name: student_outcomes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.student_outcomes_id_seq', 1, false);


--
-- Name: students_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.students_id_seq', 1, false);


--
-- Name: subject_offerings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.subject_offerings_id_seq', 1, false);


--
-- Name: universities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.universities_id_seq', 1, true);


--
-- Name: university_goals_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.university_goals_id_seq', 2, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 8, true);


--
-- Name: workflow_state_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.workflow_state_id_seq', 15, true);


--
-- Name: absence_reasons absence_reasons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.absence_reasons
    ADD CONSTRAINT absence_reasons_pkey PRIMARY KEY (id);


--
-- Name: admission_weights admission_weights_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admission_weights
    ADD CONSTRAINT admission_weights_pkey PRIMARY KEY (id);


--
-- Name: agent_action_outcomes agent_action_outcomes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_action_outcomes
    ADD CONSTRAINT agent_action_outcomes_pkey PRIMARY KEY (id);


--
-- Name: agent_audit_logs agent_audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_audit_logs
    ADD CONSTRAINT agent_audit_logs_pkey PRIMARY KEY (id);


--
-- Name: agent_decision_logs agent_decision_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_decision_logs
    ADD CONSTRAINT agent_decision_logs_pkey PRIMARY KEY (id);


--
-- Name: agent_experiences agent_experiences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_experiences
    ADD CONSTRAINT agent_experiences_pkey PRIMARY KEY (id);


--
-- Name: agent_strategies agent_strategies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_strategies
    ADD CONSTRAINT agent_strategies_pkey PRIMARY KEY (id);


--
-- Name: agent_task_context agent_task_context_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_task_context
    ADD CONSTRAINT agent_task_context_pkey PRIMARY KEY (context_key, task_id);


--
-- Name: agent_tasks agent_tasks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_tasks
    ADD CONSTRAINT agent_tasks_pkey PRIMARY KEY (task_id);


--
-- Name: app_workflow_state app_workflow_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.app_workflow_state
    ADD CONSTRAINT app_workflow_state_pkey PRIMARY KEY (id);


--
-- Name: applications applications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT applications_pkey PRIMARY KEY (id);


--
-- Name: assessments assessments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessments
    ADD CONSTRAINT assessments_pkey PRIMARY KEY (id);


--
-- Name: attendance_interventions attendance_interventions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_interventions
    ADD CONSTRAINT attendance_interventions_pkey PRIMARY KEY (id);


--
-- Name: attendance attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);


--
-- Name: batch_programs batch_programs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_programs
    ADD CONSTRAINT batch_programs_pkey PRIMARY KEY (id);


--
-- Name: batch_workflow_state batch_workflow_state_batch_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_workflow_state
    ADD CONSTRAINT batch_workflow_state_batch_id_key UNIQUE (batch_id);


--
-- Name: batch_workflow_state batch_workflow_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_workflow_state
    ADD CONSTRAINT batch_workflow_state_pkey PRIMARY KEY (id);


--
-- Name: batches batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batches
    ADD CONSTRAINT batches_pkey PRIMARY KEY (id);


--
-- Name: candidates candidates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_pkey PRIMARY KEY (id);


--
-- Name: career_outcomes career_outcomes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.career_outcomes
    ADD CONSTRAINT career_outcomes_pkey PRIMARY KEY (id);


--
-- Name: career_outcomes career_outcomes_student_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.career_outcomes
    ADD CONSTRAINT career_outcomes_student_id_key UNIQUE (student_id);


--
-- Name: certificates certificates_certificate_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT certificates_certificate_code_key UNIQUE (certificate_code);


--
-- Name: certificates certificates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT certificates_pkey PRIMARY KEY (id);


--
-- Name: certificates certificates_student_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT certificates_student_id_key UNIQUE (student_id);


--
-- Name: counseling_sessions counseling_sessions_application_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.counseling_sessions
    ADD CONSTRAINT counseling_sessions_application_id_key UNIQUE (application_id);


--
-- Name: counseling_sessions counseling_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.counseling_sessions
    ADD CONSTRAINT counseling_sessions_pkey PRIMARY KEY (id);


--
-- Name: course_exams course_exams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_exams
    ADD CONSTRAINT course_exams_pkey PRIMARY KEY (id);


--
-- Name: course_exams course_exams_subject_offering_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_exams
    ADD CONSTRAINT course_exams_subject_offering_id_key UNIQUE (subject_offering_id);


--
-- Name: email_log email_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_log
    ADD CONSTRAINT email_log_pkey PRIMARY KEY (id);


--
-- Name: enrollments enrollments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT enrollments_pkey PRIMARY KEY (id);


--
-- Name: entrance_exam_sessions entrance_exam_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entrance_exam_sessions
    ADD CONSTRAINT entrance_exam_sessions_pkey PRIMARY KEY (id);


--
-- Name: exam_halls exam_halls_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_halls
    ADD CONSTRAINT exam_halls_name_key UNIQUE (name);


--
-- Name: exam_halls exam_halls_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_halls
    ADD CONSTRAINT exam_halls_pkey PRIMARY KEY (id);


--
-- Name: exam_questions exam_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_questions
    ADD CONSTRAINT exam_questions_pkey PRIMARY KEY (id);


--
-- Name: exam_results exam_results_application_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_results
    ADD CONSTRAINT exam_results_application_id_key UNIQUE (application_id);


--
-- Name: exam_results exam_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_results
    ADD CONSTRAINT exam_results_pkey PRIMARY KEY (id);


--
-- Name: exam_schedules exam_schedules_batch_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_schedules
    ADD CONSTRAINT exam_schedules_batch_id_key UNIQUE (batch_id);


--
-- Name: exam_schedules exam_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_schedules
    ADD CONSTRAINT exam_schedules_pkey PRIMARY KEY (id);


--
-- Name: exam_submissions exam_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_submissions
    ADD CONSTRAINT exam_submissions_pkey PRIMARY KEY (id);


--
-- Name: exam_submissions exam_submissions_slot_enrollment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_submissions
    ADD CONSTRAINT exam_submissions_slot_enrollment_id_key UNIQUE (slot_enrollment_id);


--
-- Name: faculty faculty_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faculty
    ADD CONSTRAINT faculty_pkey PRIMARY KEY (id);


--
-- Name: faculty faculty_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faculty
    ADD CONSTRAINT faculty_user_id_key UNIQUE (user_id);


--
-- Name: failed_task failed_task_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.failed_task
    ADD CONSTRAINT failed_task_pkey PRIMARY KEY (id);


--
-- Name: feature_performance feature_performance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feature_performance
    ADD CONSTRAINT feature_performance_pkey PRIMARY KEY (id);


--
-- Name: goals goals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_pkey PRIMARY KEY (id);


--
-- Name: graduation_candidates graduation_candidates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_candidates
    ADD CONSTRAINT graduation_candidates_pkey PRIMARY KEY (id);


--
-- Name: graduation_candidates graduation_candidates_student_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_candidates
    ADD CONSTRAINT graduation_candidates_student_id_key UNIQUE (student_id);


--
-- Name: interview_schedules interview_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_schedules
    ADD CONSTRAINT interview_schedules_pkey PRIMARY KEY (id);


--
-- Name: join_requests join_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.join_requests
    ADD CONSTRAINT join_requests_pkey PRIMARY KEY (id);


--
-- Name: parent_notifications parent_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parent_notifications
    ADD CONSTRAINT parent_notifications_pkey PRIMARY KEY (id);


--
-- Name: programs programs_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT programs_name_key UNIQUE (name);


--
-- Name: programs programs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.programs
    ADD CONSTRAINT programs_pkey PRIMARY KEY (id);


--
-- Name: question_bank question_bank_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.question_bank
    ADD CONSTRAINT question_bank_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);


--
-- Name: semester_exam_schedules semester_exam_schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.semester_exam_schedules
    ADD CONSTRAINT semester_exam_schedules_pkey PRIMARY KEY (id);


--
-- Name: slot_enrollments slot_enrollments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slot_enrollments
    ADD CONSTRAINT slot_enrollments_pkey PRIMARY KEY (id);


--
-- Name: staff staff_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.staff
    ADD CONSTRAINT staff_pkey PRIMARY KEY (id);


--
-- Name: strategic_lessons strategic_lessons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.strategic_lessons
    ADD CONSTRAINT strategic_lessons_pkey PRIMARY KEY (id);


--
-- Name: student_credits student_credits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_credits
    ADD CONSTRAINT student_credits_pkey PRIMARY KEY (id);


--
-- Name: student_credits student_credits_student_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_credits
    ADD CONSTRAINT student_credits_student_id_key UNIQUE (student_id);


--
-- Name: student_outcomes student_outcomes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_outcomes
    ADD CONSTRAINT student_outcomes_pkey PRIMARY KEY (id);


--
-- Name: student_outcomes student_outcomes_student_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_outcomes
    ADD CONSTRAINT student_outcomes_student_id_key UNIQUE (student_id);


--
-- Name: students students_application_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_application_id_key UNIQUE (application_id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: students students_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_user_id_key UNIQUE (user_id);


--
-- Name: subject_offerings subject_offerings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_offerings
    ADD CONSTRAINT subject_offerings_pkey PRIMARY KEY (id);


--
-- Name: system_policies system_policies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_policies
    ADD CONSTRAINT system_policies_pkey PRIMARY KEY (policy_key);


--
-- Name: workflow_state uk74m2gqffgm8kh1giffp7fgwrn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_state
    ADD CONSTRAINT uk74m2gqffgm8kh1giffp7fgwrn UNIQUE (batch_id);


--
-- Name: universities universities_admin_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.universities
    ADD CONSTRAINT universities_admin_email_key UNIQUE (admin_email);


--
-- Name: universities universities_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.universities
    ADD CONSTRAINT universities_name_key UNIQUE (name);


--
-- Name: universities universities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.universities
    ADD CONSTRAINT universities_pkey PRIMARY KEY (id);


--
-- Name: universities universities_subdomain_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.universities
    ADD CONSTRAINT universities_subdomain_key UNIQUE (subdomain);


--
-- Name: university_goals university_goals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.university_goals
    ADD CONSTRAINT university_goals_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: workflow_state workflow_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_state
    ADD CONSTRAINT workflow_state_pkey PRIMARY KEY (id);


--
-- Name: idx_exp_action; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exp_action ON public.agent_experiences USING btree (action);


--
-- Name: idx_exp_goal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exp_goal ON public.agent_experiences USING btree (goal_id);


--
-- Name: idx_exp_score; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exp_score ON public.agent_experiences USING btree (score);


--
-- Name: idx_strategy_goal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_strategy_goal ON public.agent_strategies USING btree (goal_context);


--
-- Name: idx_strategy_score; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_strategy_score ON public.agent_strategies USING btree (confidence_score);


--
-- Name: idx_student_intervention; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_student_intervention ON public.attendance_interventions USING btree (student_id);


--
-- Name: interview_schedules fk106cg8rx8xpj1xr0lyjxflumd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_schedules
    ADD CONSTRAINT fk106cg8rx8xpj1xr0lyjxflumd FOREIGN KEY (interviewer_id) REFERENCES public.faculty(id);


--
-- Name: students fk10f2t900gaqoi2ahm3pm3nctq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fk10f2t900gaqoi2ahm3pm3nctq FOREIGN KEY (university_id) REFERENCES public.universities(id);


--
-- Name: exam_schedules fk2yqo3b9vnryrfrwv8815atlvm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_schedules
    ADD CONSTRAINT fk2yqo3b9vnryrfrwv8815atlvm FOREIGN KEY (batch_id) REFERENCES public.batches(id);


--
-- Name: applications fk3kdupvkbxm9frwaj0ya0rvjqu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fk3kdupvkbxm9frwaj0ya0rvjqu FOREIGN KEY (university_id) REFERENCES public.universities(id);


--
-- Name: students fk4x1jx5uvqwm9pc2xp1qmp5xms; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fk4x1jx5uvqwm9pc2xp1qmp5xms FOREIGN KEY (application_id) REFERENCES public.applications(id);


--
-- Name: subject_offerings fk7wjs7sh8x7r4ax1ojdyv3b8bf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_offerings
    ADD CONSTRAINT fk7wjs7sh8x7r4ax1ojdyv3b8bf FOREIGN KEY (faculty_id) REFERENCES public.faculty(id);


--
-- Name: agent_task_context fk885ndccf3bm03mobrrc66dxbn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_task_context
    ADD CONSTRAINT fk885ndccf3bm03mobrrc66dxbn FOREIGN KEY (task_id) REFERENCES public.agent_tasks(task_id);


--
-- Name: enrollments fk8kf1u1857xgo56xbfmnif2c51; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fk8kf1u1857xgo56xbfmnif2c51 FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: batches fk9lyowp7kiaso4ok7wsxaxbjbu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batches
    ADD CONSTRAINT fk9lyowp7kiaso4ok7wsxaxbjbu FOREIGN KEY (university_id) REFERENCES public.universities(id);


--
-- Name: student_credits fk9w7lcv79as1n1gykiixd578tl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_credits
    ADD CONSTRAINT fk9w7lcv79as1n1gykiixd578tl FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: students fka8eqoks8vbia3drc6hiqvtek7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fka8eqoks8vbia3drc6hiqvtek7 FOREIGN KEY (batch_program_id) REFERENCES public.batch_programs(id);


--
-- Name: counseling_sessions fkb1rbwnkv9u8jhgb8qnh37ivsb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.counseling_sessions
    ADD CONSTRAINT fkb1rbwnkv9u8jhgb8qnh37ivsb FOREIGN KEY (application_id) REFERENCES public.applications(id);


--
-- Name: entrance_exam_sessions fkb8iwx23rf3semfvnchdckn1ir; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entrance_exam_sessions
    ADD CONSTRAINT fkb8iwx23rf3semfvnchdckn1ir FOREIGN KEY (application_id) REFERENCES public.applications(id);


--
-- Name: batch_programs fkcypt3gvyry4o5kc5kb157cbjh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_programs
    ADD CONSTRAINT fkcypt3gvyry4o5kc5kb157cbjh FOREIGN KEY (batch_id) REFERENCES public.batches(id);


--
-- Name: career_outcomes fkd2f21e84lwhkac0wg9h4q0vwl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.career_outcomes
    ADD CONSTRAINT fkd2f21e84lwhkac0wg9h4q0vwl FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: parent_notifications fkd69secw4akomdfobkv3yi2fxh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parent_notifications
    ADD CONSTRAINT fkd69secw4akomdfobkv3yi2fxh FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: subject_offerings fkdgfvaqf7y925npo2l4put4aoq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subject_offerings
    ADD CONSTRAINT fkdgfvaqf7y925npo2l4put4aoq FOREIGN KEY (batch_id) REFERENCES public.batches(id);


--
-- Name: join_requests fkdku7pij8qiqg1471wybd70vdu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.join_requests
    ADD CONSTRAINT fkdku7pij8qiqg1471wybd70vdu FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: students fkdq4ek4hqr0unqrf0opvl6yneh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fkdq4ek4hqr0unqrf0opvl6yneh FOREIGN KEY (batch_id) REFERENCES public.batches(id);


--
-- Name: students fkdt1cjx5ve5bdabmuuf3ibrwaq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fkdt1cjx5ve5bdabmuuf3ibrwaq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: batch_programs fkdun7ps10o6fabq9rkwptcnk5w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_programs
    ADD CONSTRAINT fkdun7ps10o6fabq9rkwptcnk5w FOREIGN KEY (program_id) REFERENCES public.programs(id);


--
-- Name: faculty fkfakwwhqpm5bahy2do8t30j58r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faculty
    ADD CONSTRAINT fkfakwwhqpm5bahy2do8t30j58r FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: exam_submissions fkgtajq63l07ea6kmd7o7qsgbdv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_submissions
    ADD CONSTRAINT fkgtajq63l07ea6kmd7o7qsgbdv FOREIGN KEY (slot_enrollment_id) REFERENCES public.slot_enrollments(id);


--
-- Name: slot_enrollments fkh43uww86vspkcddmatlyruf9y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slot_enrollments
    ADD CONSTRAINT fkh43uww86vspkcddmatlyruf9y FOREIGN KEY (subject_offering_id) REFERENCES public.subject_offerings(id);


--
-- Name: exam_results fkhxt87nacwbl9cxpfprm6vw4ag; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_results
    ADD CONSTRAINT fkhxt87nacwbl9cxpfprm6vw4ag FOREIGN KEY (application_id) REFERENCES public.applications(id);


--
-- Name: join_requests fkj0neoyapbteefpritiglytl2x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.join_requests
    ADD CONSTRAINT fkj0neoyapbteefpritiglytl2x FOREIGN KEY (university_id) REFERENCES public.universities(id);


--
-- Name: counseling_sessions fkj5vkf5ae92wc1a4ce87bnwoop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.counseling_sessions
    ADD CONSTRAINT fkj5vkf5ae92wc1a4ce87bnwoop FOREIGN KEY (batch_id) REFERENCES public.batches(id);


--
-- Name: attendance fkjcpdq40wdd4axnvhkfi9jvdgp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fkjcpdq40wdd4axnvhkfi9jvdgp FOREIGN KEY (slot_enrollment_id) REFERENCES public.slot_enrollments(id);


--
-- Name: applications fkjuu391cxuemhf4jks12vfs7gl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fkjuu391cxuemhf4jks12vfs7gl FOREIGN KEY (exam_hall_id) REFERENCES public.rooms(id);


--
-- Name: exam_questions fkk93tokagwd6sa2yle8n28ywo6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_questions
    ADD CONSTRAINT fkk93tokagwd6sa2yle8n28ywo6 FOREIGN KEY (subject_offering_id) REFERENCES public.subject_offerings(id);


--
-- Name: course_exams fkkwjfsmb0osc7i49elmcp0n4dy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_exams
    ADD CONSTRAINT fkkwjfsmb0osc7i49elmcp0n4dy FOREIGN KEY (exam_hall_id) REFERENCES public.exam_halls(id);


--
-- Name: enrollments fkl197vksqb5bpealqa2o8x1wdn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enrollments
    ADD CONSTRAINT fkl197vksqb5bpealqa2o8x1wdn FOREIGN KEY (batch_id) REFERENCES public.batches(id);


--
-- Name: interview_schedules fklx2eiauxpf5ilpq0i14lp1q9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interview_schedules
    ADD CONSTRAINT fklx2eiauxpf5ilpq0i14lp1q9 FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: users fkm6cuniuttvvmhstb2s32jsotf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkm6cuniuttvvmhstb2s32jsotf FOREIGN KEY (university_id) REFERENCES public.universities(id);


--
-- Name: semester_exam_schedules fkm8ii6bvdiowxj6lghv7s2rmu4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.semester_exam_schedules
    ADD CONSTRAINT fkm8ii6bvdiowxj6lghv7s2rmu4 FOREIGN KEY (subject_offering_id) REFERENCES public.subject_offerings(id);


--
-- Name: course_exams fkmvwd85crnwnvlpu6hjwx0gmo7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_exams
    ADD CONSTRAINT fkmvwd85crnwnvlpu6hjwx0gmo7 FOREIGN KEY (subject_offering_id) REFERENCES public.subject_offerings(id);


--
-- Name: applications fkn12cfwo275diqdcubuypwpt2g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fkn12cfwo275diqdcubuypwpt2g FOREIGN KEY (batch_id) REFERENCES public.batches(id);


--
-- Name: applications fknh2osxuurfe1dtopyyxi9j4k0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.applications
    ADD CONSTRAINT fknh2osxuurfe1dtopyyxi9j4k0 FOREIGN KEY (applicant_user_id) REFERENCES public.users(id);


--
-- Name: faculty fko0ii0r1b9jj58txawlc8q7h1w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.faculty
    ADD CONSTRAINT fko0ii0r1b9jj58txawlc8q7h1w FOREIGN KEY (university_id) REFERENCES public.universities(id);


--
-- Name: candidates fko5bt89xwatyq09i6d4qt2ya6w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT fko5bt89xwatyq09i6d4qt2ya6w FOREIGN KEY (university_id) REFERENCES public.universities(id);


--
-- Name: students fkosyri4p0rpereimcss9cm3cwv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fkosyri4p0rpereimcss9cm3cwv FOREIGN KEY (program_id) REFERENCES public.programs(id);


--
-- Name: assessments fkpb25g598y95mba5pgrcs3cd0o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessments
    ADD CONSTRAINT fkpb25g598y95mba5pgrcs3cd0o FOREIGN KEY (slot_enrollment_id) REFERENCES public.slot_enrollments(id);


--
-- Name: certificates fkpc7mh1qdwwhawk8k3d8cw5y19; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT fkpc7mh1qdwwhawk8k3d8cw5y19 FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: student_outcomes fkr70l1ae7yi1wltl11w8sowkw0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_outcomes
    ADD CONSTRAINT fkr70l1ae7yi1wltl11w8sowkw0 FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: slot_enrollments fktajcuihg1h044er2k9fs5xhyt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.slot_enrollments
    ADD CONSTRAINT fktajcuihg1h044er2k9fs5xhyt FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- Name: graduation_candidates fktkswyffvinl3jxtviil3oan0k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.graduation_candidates
    ADD CONSTRAINT fktkswyffvinl3jxtviil3oan0k FOREIGN KEY (student_id) REFERENCES public.students(id);


--
-- PostgreSQL database dump complete
--

